version: '3'

vars:
  ROC_INSTALL_FOLDER: "./.bin/roc"

  SAMPLES: "../../samples"
  INPUTS: "../../inputs"

tasks:
  # ---- days ----

  d1:
    dir: days/d01
    cmds:
      - defer: rm main
      - "roc build main.roc"
      - task: run-day
        vars: { RUN: "./main", DAY: "01" }




  # ---- utils ----

  build:
    silent: true
    cmds:
      - "cd runner; cargo build -r"
      - "cp ./runner/target/release/runner ./.bin/advent"

  install-roc:
    cmds:
      - curl -OL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_apple_silicon-latest.tar.gz
      - tar xf roc_nightly-macos_apple_silicon-latest.tar.gz
      - rm roc_nightly-macos_apple_silicon-latest.tar.gz
      - rm -rf {{ .ROC_INSTALL_FOLDER }}
      - mkdir {{ .ROC_INSTALL_FOLDER }}
      - mv roc_nightly-macos_apple_silicon-*/* {{ .ROC_INSTALL_FOLDER }}
      - rm -d roc_nightly-macos_apple_silicon-*

  install-gleam:
    cmds:
      - brew install gleam # will install both Gleam and Erlang
